config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'likes_posts'
    end
  end
  
  resources :posts, only: [:index, :show, :new, :create, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :likes_users, through: :likes, source: :user
  
  validates :content, presence: true, length: { maximum: 255 }
  validates :image, presence: true
  
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum:50 }
    validates :introduce, length: { maximum:255 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    
    has_many :posts, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :likes_posts, through: :likes, source: :post
    
    def already_liked?(post)
        self.likes.exists?(post_id: post.id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include SessionsHelper
    
    private
    
    def require_user_logged_in
        unless logged_in?
        redirect_to login_url
        end
    end
    
    def counts(user)
        @count_posts = user.posts.count
        @count_likes_posts = user.likes_posts.count
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    flash[:success] = 'いいねしました。'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    flash[:success] = 'いいねを解除しました。'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in, only: [:new, :show]
  before_action :correct_user, only: [:destroy]
  
  def index
    @posts = Post.order(id: :desc).page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
   
  end

  def new
    if logged_in?
      @post = current_user.posts.build
    end
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = '投稿しました。'
      redirect_to root_url
    else
      flash.now[:danger] = '投稿できませんでした。'
      render :new
    end
  end

  def destroy
    @post.destroy
    flash[:success] = '投稿を削除しました。'
    redirect_to root_url
  end
  
  private
  
  def post_params
    params.require(:post).permit(:image, :content)
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
    redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :edit, :update, :destroy, :likes_posts]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
      
      if @user.update(user_params)
        flash[:success] = 'プロフィールを変更しました。'
        redirect_to @user
      else
        flash.now[:danger] = 'プロフィールを変更できませんでした。'
        render :edit
      end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = '退会しました。'
    redirect_to root_url
  end
  
  def likes_posts
    @user = User.find(params[:id])
    @likes_posts = @user.likes_posts.page(params[:page])
    counts(@user)
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :introduce)
  end

  def correct_user
    @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !!current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_url(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
      <ul class="mb-0">
          <% model.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
      </ul>
  </div>
<% end %>  

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type,message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Telegram</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
              <% if logged_in? %>
                <li class="nav-item"><%= link_to 'ユーザ', users_path, class: 'nav-link' %></li>
                <li class="nav-item"><%= link_to '投稿する', new_post_path, class: 'nav-link' %></li>
                <li class="nav-item dropdown">
                  <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
                  <ul class="dropdown-menu dropdown-menu-right">
                      <li class="dropdown-item"><%= link_to 'プロフィール', user_path(current_user) %></li>
                      <li class="dropdown-divider"></li>
                      <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
                  </ul>
                 </li>
              <% else %>
                <li class="nav-item"><%= link_to '新規登録', signup_path, class: 'nav-link' %></li>
                <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
              <% end %>
            </ul>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Telegram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/likes/_likes_button.html.erb
<% if current_user.already_liked?(post) %>
  <%= form_with(model: current_user.likes.find_by(post_id: post.id), local: true, method: :delete) do |f| %>
    <%= hidden_field_tag :post_id, post.id %>
    <%= f.submit 'いいねを解除', class: 'btn btn-secondary btn-sm' %>
  <% end %>
<% else %>
  <%= form_with(model: current_user.likes.build, local: true) do |f| %>
    <%= hidden_field_tag :post_id, post.id %>
    <%= f.submit 'いいね', class: 'btn btn-secondary btn-sm' %>
  <% end %>
<% end %>

app/views/posts/_posts.html.erb
<ul class="list-styled">
  <% posts.each do |post| %>
   <li class="media">
     <img src="<%= gravatar_url(post.user, { size: 50 }) %>" class="mr-3" alt="...">
     <div class="media-body">
       <div>
          <%= link_to post.user.name, user_path(post.user) %><span class="text-muted">posted at <%= post.created_at %></span>
       </div>
       <div>
          <p>
              <%= image_tag post.image.url if post.image? %>
          </p>
       </div>
       <div>
           <p><%= link_to simple_format(h(post.content)), post_path(post) %></p>
       </div>
       <div class="mb-5">
           <a href="<%= post_path(post) %>" class="badge badge-secondary" >いいね数<%= post.likes.count %></a>
       </div>
   </li>
  <% end %>
  <%= paginate posts %>
</ul>  

app/views/posts/index.html.erb
<%= render 'posts/posts', posts: @posts %>

app/views/posts/new.html.erb
<div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= form_with(model: @post, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <div class="field">
          <%= f.label :image, '画像選択' %>
          <%= f.file_field :image, class: 'form-control' %>
        </div>
      </div>
    
      <div class="form-group">
        <%= f.text_area :content, class: 'form-control' %>
      </div>
        <%= f.submit '投稿',class: 'btn btn-primary btn-block' %>
     <% end %>
    </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="list-styled">
    <div class="media">
      <img src="<%= gravatar_url(@post.user, { size: 50 }) %>" class="mr-3" alt="...">
        <div class="media-body">
          <div>
            <%= link_to @post.user.name, user_path(@post.user) %><span class="text-muted">posted at <%= @post.created_at %></span>
          </div>
        <div>
          <p>
              <%= image_tag @post.image.url if @post.image? %>
          </p>
        </div>
        <div>
           <p><%= simple_format(h(@post.content)) %></p>
        </div>
        <div class="d-flex justify-content-start">
        <div class="mr-3">
           <% if current_user.already_liked?(@post) %>
             <%= link_to 'いいねを解除', post_like_path(@post), method: :delete, class: 'btn btn-secondary btn-sm' %>
           <% else %>
             <%= link_to 'いいね', post_likes_path(@post), method: :post, class: 'btn btn-secondary btn-sm' %>
           <% end %>
        </div>
        <div>
          <% if current_user == @post.user %>
            <%= link_to '投稿の削除', @post, method: :delete, data: { confirm: "本当によろしいですか？" }, class: 'btn btn-danger btn-sm' %>
          <% end %>
       </div>
       </div>
       <h4 class="mt-3">「いいね」したユーザ (<%= @post.likes.count %>)</h4>
        <% @post.likes_users.each do |user| %>
          <li><%= link_to user.name, user_path(user) %></li>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="text-center">
    <h1>プロフィール編集</h1>
</div>

<div class="row">
    <div class="col-sm-6 offset-sm-3">
        <%= form_with(model: @user, local: true) do |f| %>
        <div class="form-group">
            <%= f.label :name, '名前' %>
            <%= f.text_field :name, class: 'form-control' %>
        </div>
        
        <div class="form-group">
            <%= f.label :email,'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
        </div>
        
        <div class="form-group">
            <%= f.label :introduce, '自己紹介' %>
            <%= f.text_area :introduce, class: 'form-control' %>
        </div>
        <%= f.submit '編集を完了する', class: 'btn btn-primary btn-block' %>
        <% end %>
        <%= link_to '退会', user_path(current_user), method: :delete, data: { confirm: "本当に退会しますか？" }, class: 'btn btn-danger mt-5' %>
    </div>
</div>

app/views/users/index.html.erb
<% if @users.any? %>
  <ul class="list-unstyled">
      <% @users.each do |user| %>
        <li class="media">
            <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
            <div class="media-body">
                <div>
                    <%= user.name %>
                </div>
                <div>
                    <p><%= link_to 'プロフィール', user_path(user) %></p>
                </div>
            </div>
        </li>
       <% end %>
  </ul>
  <%= paginate @users %>
<% end %>  

app/views/users/likes_posts.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="cord-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <div class="mt-5">
      <% if current_user == @user %>
        <%= link_to '投稿する', new_post_path, class: 'btn btn-secondary btn-block' %>
      <% end %>
    </div>
  </aside>
  <div class="col-sm-8 col align-self-center">
      <h2>プロフィール</h2>
      <% if current_user == @user %>
        <%= link_to edit_user_path do %>
          <i class="fas fa-cog"></i>
        <% end %>
      <% end %>
      <p><%= @user.introduce %></p>
    </div>
  </div>
  <div class="mt-5">
        <ul class="nav nav-tabs nav-justified mb-3">
          <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿一覧 <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
          <li class="nav-item"><a href="<%= likes_posts_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_posts_user_path(@user)) %>">いいね一覧 <span class="badge badge-secondary"><%= @count_likes_posts %></span></a></li>
        </ul>
        <%= render 'posts/posts', posts: @likes_posts %>
    </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
    <h1>新規登録</h1>
</div>

<div class="row">
    <div class="col-sm-6 offset-sm-3">
        
        <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        
          <div class="form-group">
              <%= f.label :name, '名前' %>
              <%= f.text_field :name, class: 'form-control' %>
          </div>
          
          <div class="form-group">
              <%= f.label :email, 'メールアドレス' %>
              <%= f.email_field :email, class: 'form-control' %>
          </div>
          
          <div class="form-group">
              <%= f.label :password, 'パスワード' %>
              <%= f.password_field :password, class: 'form-control' %>
          </div>
          
          <div class="form-group">
              <%= f.label :password_confirmation, '確認用パスワード' %>
              <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          
          <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="cord-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <div class="mt-5">
      <% if current_user == @user %>
        <%= link_to '投稿する', new_post_path, class: 'btn btn-secondary btn-block' %>
      <% end %>
    </div>
  </aside>
  <div class="col-sm-8 col align-self-center">
      <h2>プロフィール</h2>
      <% if current_user == @user %>
        <%= link_to edit_user_path do %>
          <i class="fas fa-cog"></i>
        <% end %>
      <% end %>
      <p><%= simple_format(h(@user.introduce)) %></p>
    </div>
  </div>
  <div class="mt-5">
        <ul class="nav nav-tabs nav-justified mb-3">
          <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿一覧 <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
          <li class="nav-item"><a href="<%= likes_posts_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_posts_user_path(@user)) %>">いいね一覧 <span class="badge badge-secondary"><%= @count_likes_posts %></span></a></li>
        </ul>
        <%= render 'posts/posts', posts: @posts %>
    </div>
</div>